"""add_bio_avatar_emoji_to_user

Revision ID: 0c06ee5d0c53
Revises: ceeb15547171
Create Date: 2026-04-01 09:53:14.402018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c06ee5d0c53'
down_revision: Union[str, None] = 'ceeb15547171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('avatar_emoji', sa.String(length=10), server_default='🔥', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_emoji')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
